[package]
name = "genrust"
version = "1.0.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
tikv-jemallocator = { version = "0.5", features = ["profiling"] }
clap = { version = "4.0", features = ["derive"] }
regex = "1"
serde_json = "*"
